### ISSUE TITLE
whatsapp crypt7 file restore error - xtract v 2.5

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cesarlavigne/hotoloti#16]
```


D:\PST file>python "D:\PST file\whatsapp_xtract.py" "D:\PST file\msgstore-2014-0
5-14.1.db.crypt7"
Python Version 2.x

Detected non-SQLite database, potentially an encrypted Android database
Trying to decrypt Android database...
Traceback (most recent call last):
  File "D:\PST file\whatsapp_xtract.py", line 2670, in <module>
    main(sys.argv[1:])
  File "D:\PST file\whatsapp_xtract.py", line 1435, in main
    decoded = cipher.decrypt(open(options.infile,"rb").read())
  File "C:\Users\pskumar1.VECVNET\AppData\Roaming\Python\Python27\site-packages\
Crypto\Cipher\blockalgo.py", line 295, in decrypt
    return self._cipher.decrypt(ciphertext)
ValueError: Input strings must be a multiple of 16 in length
Press any key to continue . . .
```

Original issue reported on code.google.com by `prashant...@gmail.com` on 21 May 2014 at 11:56

**Comment by GoogleCodeExporter** [comment]
```
I am also getting the same error and i m not able to decrypt my messages till 
now. Can any one help on this how to decrypt crypt7 database with key file.
```

Original comment by `praveen....@gmail.com` on 15 Aug 2014 at 5:47

**Comment by GoogleCodeExporter** [comment]
```
u can not decrypt crypt7 database without key file! 
if your phone is rooted do this:
http://www.backuptrans.com/tutorial/extract-key-file-to-open-whatsapp-crypt-file
.html
if not rooted do this:
http://forum.xda-developers.com/showthread.php?t=2770982
```

Original comment by `sww...@gmail.com` on 18 Aug 2014 at 6:30

**Comment by GoogleCodeExporter** [comment]
```
I followed the steps given here and it worked for me : 
http://www.digitalinternals.com/security/decrypt-whatsapp-crypt7-database-messag
es/307/

I have a non-rooted Nexus 5 and was successful to decrypt the database on 
Ubuntu 13.04

Now I'm looking for encrypting the database to crypt7 so that I can restore it 
back on whatsapp with modified chat. I someone happen to know how to do it, hit 
me an email.
```

Original comment by `akhanda...@gmail.com` on 19 Aug 2014 at 7:30

**Comment by GoogleCodeExporter** [comment]
```
Hi,
thank you very much!
```

Original comment by `francesco.picasso` on 25 Nov 2014 at 4:12
- Changed state: **WontFix**

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
hi..but can we find a way to find how these cipher keys are generated? Coz der 
is a neccesity for the key file in order to decrypt the database.

```

Original comment by `danielfd...@gmail.com` on 18 Dec 2014 at 11:10
