### ISSUE TITLE
Windows Phone Whatsapp messages.db decryption possible?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cesarlavigne/hotoloti#17]
```
What steps will reproduce the problem?
1. Try to decrypt messages.db from Windows Phone backup
2. Invalid format error

What is the expected output? What do you see instead?
I would like to decrypt or extract the database of messages from my whatsapp 
backup.

What version of the product are you using? On what operating system?
Windows Phone 7.5, 8, 8.1 - latest Whatsapp verison



```

Original issue reported on code.google.com by `jdd...@gmail.com` on 17 Aug 2014 at 6:34

**Comment by GoogleCodeExporter** [comment]
```
Not working on it, sorry
```

Original comment by `francesco.picasso` on 25 Nov 2014 at 4:12
- Changed state: **Done**

**Comment by GoogleCodeExporter** [comment]
```

C:\Users\xxxxxxxxxxxxx\Whatsapp_Xtract_V2.1_2012-05-10-2>pytho
n whatsapp_xtract.py ChatStorage.sqlite
Python Version 2.x

Detected an SQLite database
Android mode!
Checking Android database integrity...
Android database has integrity issues. Attempting to fix it...
Traceback (most recent call last):
  File "whatsapp_xtract.py", line 2785, in <module>
    main(sys.argv[1:])
  File "whatsapp_xtract.py", line 1611, in main
    f2.write("COMMIT;");
TypeError: must be unicode, not str

C:\Users\xxxxxxxxx\Whatsapp_Xtract_V2.1_2012-05-10-2>pause

Premere un tasto per continuare . . .



```

Original comment by `luca.zig...@gmail.com` on 24 Jul 2015 at 7:57
